### ISSUE TITLE
The PATCH route doesn't prevent duplicate attachments

### ISSUE THREAD

**Issue by Ghabriel** [alexpensato/laravel-api-maker#1]
Consider a many-to-many relationship between models *A* and *B*. If I run the following queries:

```
PATCH /A?attach=B
{
    "A": [
        {
            "id": 1,
            "B": [1]
        }
    ]
}
```

```
PATCH /A?attach=B
{
    "A": [
        {
            "id": 1,
            "B": [1, 2]
        },
        {
            "id": 2,
            "B": [1, 2]
        }
    ]
}
```

Expected output:

id | A_id | B_id
-- | ---- | ----
1 | 1 | 1
2 | 1 | 2
3 | 2 | 1
4 | 2 | 2

Actual output:

id | A_id | B_id
-- | ---- | ----
1 | 1 | 1
2 | 1 | 1
3 | 1 | 2
4 | 2 | 1
5 | 2 | 2

**Comment by alexpensato** [comment]
Thanks for the detailed report. It is now fixed!
